project:
  type: website
  output-dir: docs

website:
  title: "quarto-lit-base"
  page-navigation: true
  # site-url:
  # repo-url:
  search: true
  sidebar:
    style: "docked"
    search: true
    background: primary
    contents:
      - href: index.qmd
        text: Home
      - about.qmd
      - listing-topics.qmd
      - listing-books.qmd
    # tools:
    #   - icon: github
    #     href: https://github.com path
    # page-footer:
    #   center:
    #     - text: "About"
    #       href: about.qmd
    #     - text: "License"
    #       href: license.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



