on:
  push:
    branches: main

name: Render and Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          # To install LaTeX to build PDF book
          tinytex: true
          # uncomment below and fill to pin a version
          # version: 0.9.600

      # add software dependencies here



       - name: Publish to GitHub Pages (and render)
         uses: quarto-dev/quarto-actions/publish@v2
         with:
           target: gh-pages
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this secret is always available for github actionson:


project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  reader-mode: true
  repo-url: https://github.com/icrichmond/quarto-lit-base
  repo-actions: [edit, issue]
  navbar:
    title: 'Quarto lit base'
    right:
      - icon: github
        href: https://github.com/icrichmond/quarto-lit-base
  sidebar:
    contents:
      - index.qmd
      - topics.qmd
      - books.qmd
      - papers.qmd
      - projects.qmd



format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
