project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  reader-mode: true
  repo-url: https://github.com/robitalec/quarto-lit-base
  repo-actions: [edit, issue]
  navbar:
    title: 'Quarto lit base'
    right:
      - icon: github
        href: https://github.com/robitalec/quarto-lit-base
  sidebar:
    contents:
      - index.qmd
      - topics.qmd
      - books.qmd
      - papers.qmd
      - projects.qmd



format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
