project:
  type: website
  output-dir: docs
website:
  navbar:
    title: 'Quarto lit base'
  sidebar:
    style: "docked"
    contents:
      - index.qmd
      - topics.qmd
      - books.qmd
      - projects.qmd