# Linteau_2000

Linteau, P.A. (2000) Histoire de Montréal depuius la Confédération 2e Ed. Montreal: Boréal. Available at: https://concordiauniversity.on.worldcat.org/search/detail/44795862?queryString=Histoire%20de%20Montr%C3%A9al%20depuis%20la%20Conf%C3%A9d%C3%A9ration.&databaseList= .

------------------------------------------------------------------------

Keywords: [Canada](../topics/Canada.qmd), [Montreal](../topics/Montreal.qmd), [historical](../topics/Historical.qmd)

### Chapter 8: Une expansion territoriale tous azimuts

-   mid 19th century (1896-1913) the suburbs Montreal started to expand significantly, the landscape of montreal changed

-   expansion southwest was industrial, west was rich anglophones, north was residential

-   new factories were located on the Lachine canal and in Hochelaga-Maisonneuve

-   many public services were added in the expansion

-   along with construction, the general consensus (based on trends from the US) was that we needed "urban beautification" from parks and grand boulevards

### Chapter 9: Vivre a la belle époque

-   La belle eqpoque refers to the period of prosperity and happiness experienced from 1896-1914 in Canada and other large industrial nations

-   For wealthy people, it was the golden age

    -   Allowing colossal accumulation of fortunes for capitalists, paying little taxes

-   the majority of Montreal was under the poverty line

-   there was beginning to be a movement across the world where workers were becoming more aggressive that they needed better conditions to work in industry/cities

    -   housing, health (mortality, infant mortality, water quality, and tuberculosis), inequitable social services, education were all important in the movement

-   the tramway was regarded as essential to city life

    -   it was particularly important to park entertainment

    -   parks offered different entertainment and were connected to the people via tramways

    -   Attraction parks such as Dominion Park were private enterprises

-   Public parks were limited in this period, but Montreal had two important parks - Mont-Royal and Ile Saint-Helene

    -   At the end of the 19th century, Montreal opened Parc Lafontaine on what was Logan Farm -- it was very popular especially w francophones

    -   The Grands Parcs were created here, to manage landscaping and aesthetics

-   From the beginning of the 1900s, there was a clear desire for parks to be places of recreation, that could respond to the wide variety of needs of the urban population

    -   This direction led to the creation of neighbourhood parks and public squares

-   The Parks and Playground Association was founded in 1902 by Julia Drummond, which is when playgrounds started to be developed in city parks

-   the scene of Montreal changed drastically in a few years

### Chapter 13: L'espace: continuité et nouveauté

-   there was a pause in suburbanization in between the two world wars

-   suburbanization developed agricultural and forested lands

-   development of services and houses began to happen within montreal as well
