# Dean_2005

Dean J (2005) "Said tree is a veritable nuisance": Ottawa's Street Trees 1869-1939 Urban History Review 34(1):28-45. https://www.jstor.org/stable/43562344

------------------------------------------------------------------------

Keywords: [Canada](../topics/Canada.qmd), [historical](../topics/Historical.qmd), [urban trees](../topics/UrbanTrees.qmd)

-   Street trees were planted in the second half of the nineteenth century across North America

-   Ottawa's urban forest peaked in 1932

    -   Horticultural Society lobbied for less trees that were better maintained

-   Many of the most vocal defenders of forests in the 1800s/1900s lived in cities

    -   the rise of the environmental movement followed Dutch Elm Disease in urban neighbourhoods

-   Ottawa implemented a ordinance to encourage tree planting in 1869, and then the trees were aggressively removed and pruned in the 1920s

-   When Ottawa was urbanized, all trees were removed

-   Ottawa as the capital was disappointed that the Americans had more trees in their cities and followed suit

-   Street trees became a sign of wealth and when they were removed, residents were compensated

-   The relationship between street trees and society evolved, until they served a smaller, specific role managed by the city
