# Nelles_2005

Nelles HV (2005) How Did Calgary Get Its River Parks? Urban History Review 34(1):28-45. https://www.jstor.org/stable/43562343

------------------------------------------------------------------------

Keywords: [Canada](../topics/Canada.qmd), [historical](../topics/Historical.qmd), [parks](../topics/Parks.qmd), [landuse](../topics/LandUse.qmd)

-   Mid-twentieth century, the perception of parks and the Bow river changed

-   In democracy, parks are viewed as leisure and affluence (we can use this space for something "non-productive"). Post-World War era was a surge of leisure and affluence, thus a changing perception of the river/parks came into being

-   The river was not always a park, the city developed with the river serving industrial and commercial purposes

-   Traditionally a working class living area - south bank of the river. The river was considered a "junkyard"

-   Visiting urban planner used "City Beautiful" movement techniques to propose a new city design for Calgary - plamted the seeds for a haphazard collection of parks that began to grow

-   In the 50s, Calgary Local Council of Women campaigned to improve social services and public amenities, including a ribbon of park along the river
